
---
title: Template for .Rmd
output: 
  pdf_document:
    latex_engine: xelatex
    toc:  TRUE
    toc_depth:  1
fontsize: 12pt
geometry: margin=0.5in,top=0.25in
#  md_document:
#  html_document:
#    toc: true
#  	toc_float: true
#    css: styles.css
---

---
/home/jim/.config/nvim/templates/skeleton.Rmd
othercomments
---

<!--  commments -->

```{r setup, include=FALSE		}
knitr::opts_chunk$set(echo = TRUE,  comment="      ##",  error=TRUE, collapse=TRUE)
```

```{r library, include=FALSE		}
library(jimTools)
library(here)
library(dplyr)
library(tibble)
```


```{r render, eval=FALSE	}
here()
file <- "/home/jim/code/r_rafael/rmd/005_linear_algebra_examples.Rmd"
file  <- basename(file)
dir="rmd"

jimTools::ren_pdf(file,dir)
jimTools::ren_github(file, dir)
```


```{r}
library("rtweet")
friends  <- rtweet::get_friends("jimrothstein")
search_tweets
lookup  <- lookup_tweets(friends[[2]])

dplyr::glimpse(lookup[[3]])

```
```{r}
rt <- search_tweets(
  "#rstats", n = 200, include_rts = FALSE
)
rt$name
names(rt) %>% head(20)
rt$text


rt %>% 
	select("created_at", "screen_name", "text") %>% 
	head()
```

```{r knit_exit()}
knitr::knit_exit()
```

***






